server:
    port: 9080
spring:
  devtools:
    restart:
      exclude:  public/**
      enabled:  true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

